/* ==========================================================================
   cittas.js — සිත් වර්ග, the eighty-nine

   The Abhidhamma classification of consciousness. The point this board is
   built to make: the 89 are not a list anyone memorised item by item. They
   are generated by a small set of fields, most of them binary — which makes
   the whole thing a bit-field, and makes the count fall out of the fields
   rather than being asserted.

   Source layer: Abhidhammattha Saṅgaha, the standard Theravāda manual. Not
   the suttas. The micro board says the same thing about its own material.
   ========================================================================== */

import { iconAt, icon } from "./icons.js";

const MOTION =
  typeof window === "undefined" ||
  !window.matchMedia("(prefers-reduced-motion: reduce)").matches;

/* ---------- the four spheres ---------- */

export const SPHERES = [
  {
    id: "kama", pali: "kāmāvacara", si: "කාමාවචර", n: 54,
    label: "sense sphere",
    d: "The ordinary mind — the one reading this. Everything that arises in the course of a normal day is one of these 54.",
  },
  {
    id: "rupa", pali: "rūpāvacara", si: "රූපාවචර", n: 15,
    label: "fine-material",
    d: "The jhāna states developed on a material object. Five jhānas, each in three modes: wholesome, resultant, functional. 5 × 3 = 15.",
  },
  {
    id: "arupa", pali: "arūpāvacara", si: "අරූපාවචර", n: 12,
    label: "immaterial",
    d: "The four formless attainments — infinite space, infinite consciousness, nothingness, neither-perception-nor-non-perception. Again in three modes. 4 × 3 = 12.",
  },
  {
    id: "lokuttara", pali: "lokuttara", si: "ලෝකෝත්තර", n: 8,
    label: "supramundane",
    d: "Four paths and their four fruitions. Counted again against the five jhāna factors they can occur with, these 8 become 40 — which is how the total of 89 becomes 121.",
  },
];

/* ---------- the 54, broken open ---------- */

export const KAMA = [
  {
    id: "akusala", pali: "akusala", si: "අකුසල", n: 12, tone: "hot",
    label: "unwholesome",
    parts: [
      ["lobha-mūla", "ලෝභමූලික", 8, "greed-rooted — and these eight are the clearest bit-field in the whole system"],
      ["dosa-mūla", "දෝසමූලික", 2, "hatred-rooted — always with displeasure, prompted or not"],
      ["moha-mūla", "මෝහමූලික", 2, "delusion-rooted — doubt, and restlessness"],
    ],
    d: "Rooted in greed, hatred or delusion. These are the ones that make kamma in the unwholesome direction, and they only ever arise at the javana stage.",
  },
  {
    id: "ahetuka", pali: "ahetuka", si: "අහේතුක", n: 18, tone: "cool",
    label: "rootless",
    parts: [
      ["akusala-vipāka", "අකුසල විපාක", 7, "results of past unwholesome action"],
      ["kusala-vipāka", "කුසල විපාක", 8, "results of past wholesome action"],
      ["ahetuka kiriya", "අහේතුක ක්‍රියා", 3, "functional — including the two adverting moments and the smile of an arahant"],
    ],
    d: "No root at all — neither greed nor its opposites. Seeing, hearing, smelling, tasting, touching, receiving and examining all live here. This is most of what the seventeen-moment series on the micro board is made of.",
  },
  {
    id: "sobhana", pali: "kāma-sobhana", si: "කාමාවචර සෝභන", n: 24, tone: "grow",
    label: "beautiful",
    parts: [
      ["mahākusala", "මහා කුසල", 8, "wholesome — the other clean bit-field, and the mirror of the greed-rooted eight"],
      ["mahāvipāka", "මහා විපාක", 8, "their results"],
      ["mahākiriya", "මහා ක්‍රියා", 8, "the same eight in an arahant, who makes no more kamma with them"],
    ],
    d: "Accompanied by the beautiful mental factors. Note the symmetry: eight wholesome, eight results, eight functional — the functional set exists because an arahant still acts, and the acting no longer writes anything.",
  },
];

/* ---------- the decoder: how eight is generated from three bits ---------- */

export const DECODERS = {
  lobha: {
    label: "the eight greed-rooted",
    pali: "lobha-mūla citta",
    si: "ලෝභමූලික සිත් අට",
    note:
      "Three binary fields, and eight is what you get. Nobody had to count these — they fall out.",
    fields: [
      { key: "feeling", label: "feeling", si: "වේදනා",
        opts: [
          ["somanassa-sahagataṃ", "සෝමනස්ස", "with joy"],
          ["upekkhā-sahagataṃ", "උපේක්ඛා", "with equanimity"],
        ] },
      { key: "view", label: "view", si: "දිට්ඨි",
        opts: [
          ["diṭṭhigata-sampayuttaṃ", "සම්පයුත්ත", "with wrong view"],
          ["diṭṭhigata-vippayuttaṃ", "විප්පයුත්ත", "without wrong view"],
        ] },
      { key: "prompt", label: "prompting", si: "සංඛාර",
        opts: [
          ["asaṅkhārikam", "අසංඛාරික", "unprompted"],
          ["sasaṅkhārikam", "සසංඛාරික", "prompted"],
        ] },
    ],
    ex: [
      "Delighted by something and quietly certain it is really yours to keep. Nobody suggested it.",
      "The same delight and the same certainty — but someone talked you into it first.",
      "Straightforward enjoyment of something you want. No theory attached to it.",
      "The same enjoyment, arrived at after being encouraged.",
      "Wanting it flatly, with the underlying conviction that having it will settle something.",
      "The same flat wanting and the same conviction, on someone else's urging.",
      "Reaching for the phone. No pleasure in it, no theory about it, and nobody prompted you.",
      "The same reaching, after a nudge.",
    ],
  },
  mahakusala: {
    label: "the eight wholesome",
    pali: "mahākusala citta",
    si: "මහා කුසල සිත් අට",
    note:
      "The same shape, with one field swapped: wrong view becomes knowledge. The symmetry is the argument.",
    fields: [
      { key: "feeling", label: "feeling", si: "වේදනා",
        opts: [
          ["somanassa-sahagataṃ", "සෝමනස්ස", "with joy"],
          ["upekkhā-sahagataṃ", "උපේක්ඛා", "with equanimity"],
        ] },
      { key: "view", label: "knowledge", si: "ඤාණ",
        opts: [
          ["ñāṇa-sampayuttaṃ", "සම්පයුත්ත", "with knowledge"],
          ["ñāṇa-vippayuttaṃ", "විප්පයුත්ත", "without knowledge"],
        ] },
      { key: "prompt", label: "prompting", si: "සංඛාර",
        opts: [
          ["asaṅkhārikam", "අසංඛාරික", "unprompted"],
          ["sasaṅkhārikam", "සසංඛාරික", "prompted"],
        ] },
    ],
    ex: [
      "Giving gladly, understanding exactly why it matters, with nobody asking.",
      "The same gladness and understanding, after someone suggested it.",
      "Giving gladly out of warmth or habit, with no reflection behind it.",
      "The same, prompted.",
      "Acting rightly and understanding why, with no particular feeling about it either way.",
      "The same clear-eyed act, on someone's urging.",
      "Doing the right thing flatly, because it is what you do.",
      "The same, after being asked.",
    ],
  },
};

/* The standard ordering: feeling is the high bit, then view, then prompting. */
export function decode(mode, bits) {
  const i = bits.feeling * 4 + bits.view * 2 + bits.prompt;
  const d = DECODERS[mode];
  const name = d.fields
    .map((f) => f.opts[bits[f.key]][0])
    .join(" ");
  const si = d.fields.map((f) => f.opts[bits[f.key]][1]).join(" · ");
  const plain = d.fields.map((f) => f.opts[bits[f.key]][2]).join(", ");
  return { i, name, si, plain, ex: d.ex[i] };
}

/* ---------- the 52 mental factors ---------- */

export const CETASIKA = [
  {
    pali: "sabbacittasādhāraṇa", si: "සබ්බචිත්ත සාධාරණ", n: 7,
    label: "in every single citta",
    items: "phassa · vedanā · saññā · cetanā · ekaggatā · jīvitindriya · manasikāra",
    d: "Contact, feeling, perception, intention, one-pointedness, life faculty, attention. No consciousness of any kind occurs without all seven.",
  },
  {
    pali: "pakiṇṇaka", si: "පකිණ්ණක", n: 6,
    label: "occasional",
    items: "vitakka · vicāra · adhimokkha · vīriya · pīti · chanda",
    d: "Applied thought, sustained thought, decision, energy, rapture, desire-to-act. Present in some cittas and not others, and ethically neutral in themselves.",
  },
  {
    pali: "akusala cetasika", si: "අකුසල චෛතසික", n: 14,
    label: "unwholesome",
    items: "moha, ahirika, anottappa, uddhacca (in all four) · lobha, diṭṭhi, māna · dosa, issā, macchariya, kukkucca · thīna, middha · vicikicchā",
    d: "The first four accompany every unwholesome citta without exception. The rest arrive in fixed groups — greed never travels with hatred, for instance.",
  },
  {
    pali: "sobhana cetasika", si: "සෝභන චෛතසික", n: 25,
    label: "beautiful",
    items: "19 common to all beautiful cittas · 3 abstinences · 2 immeasurables · 1 wisdom faculty",
    d: "Mindfulness, shame, moral dread, non-greed, non-hatred and the rest. The three abstinences are right speech, action and livelihood — the ethics layer, appearing here as mental factors.",
  },
];

/* ---------- board ---------- */

function sphereCol(s, i) {
  const x = 40 + i * 282;
  return `
    <g class="ct-mod" data-sphere="${s.id}" role="button" tabindex="0"
       aria-label="${s.pali}, ${s.n} types">
      <rect x="${x}" y="118" width="262" height="96" rx="10" class="ct-rect"/>
      <text x="${x + 20}" y="150" class="ct-count">${s.n}</text>
      <text x="${x + 78}" y="145" class="ct-name">${s.pali}</text>
      <text x="${x + 78}" y="160" class="ct-si">${s.si}</text>
      <text x="${x + 20}" y="186" class="ct-small">${s.label}</text>
      <text x="${x + 20}" y="202" class="ct-small">${i === 3 ? "×5 jhāna factors → 40" : " "}</text>
    </g>`;
}

function kamaBlock(k, i) {
  const x = 40 + i * 378;
  const rows = k.parts
    .map(([p, si, n, d], j) => {
      const y = 330 + j * 46;
      return `
        <text x="${x + 20}" y="${y}" class="ct-partn">${n}</text>
        <text x="${x + 58}" y="${y - 6}" class="ct-partname">${p}</text>
        <text x="${x + 58}" y="${y + 8}" class="ct-si">${si}</text>
        <text x="${x + 58}" y="${y + 22}" class="ct-small">${d}</text>`;
    })
    .join("");

  return `
    <g class="ct-mod" data-kama="${k.id}" role="button" tabindex="0"
       aria-label="${k.pali}, ${k.n} types">
      <rect x="${x}" y="256" width="358" height="214" rx="10" class="ct-rect ct-rect--${k.tone}"/>
      <text x="${x + 20}" y="290" class="ct-count">${k.n}</text>
      <text x="${x + 78}" y="285" class="ct-name">${k.pali}</text>
      <text x="${x + 78}" y="300" class="ct-si">${k.si}</text>
      ${rows}
    </g>`;
}

function cetasikaRow(c, i) {
  const y = 556 + i * 52;
  return `
    <g class="ct-cet">
      <text x="56" y="${y}" class="ct-partn">${c.n}</text>
      <text x="104" y="${y - 7}" class="ct-partname">${c.pali}</text>
      <text x="104" y="${y + 7}" class="ct-si">${c.si}</text>
      <text x="320" y="${y - 7}" class="ct-small">${c.label}</text>
      <text x="320" y="${y + 7}" class="ct-items">${c.items}</text>
    </g>`;
}

export function cittasView() {
  return `
  <div class="cittas" data-cittas>
    <div class="machine__scroller">
      <svg class="cittas__svg" viewBox="0 0 1200 800" role="img"
           aria-label="The eighty-nine types of consciousness: four spheres across the top, the fifty-four sense-sphere cittas broken into unwholesome, rootless and beautiful, and the fifty-two mental factors below.">
        <rect x="12" y="12" width="1176" height="776" rx="14" class="mx-board"/>
        <text x="36" y="44" class="ct-title">සිත් වර්ග · the eighty-nine</text>
        <text x="36" y="64" class="ct-small">not a list anybody memorised item by item. a small set of fields, and the count falls out of them.</text>

        <text x="36" y="102" class="ct-group">the four spheres · 54 + 15 + 12 + 8 = 89</text>
        ${SPHERES.map(sphereCol).join("")}

        <text x="36" y="242" class="ct-group">and the 54 you are actually in, broken open</text>
        ${KAMA.map(kamaBlock).join("")}

        <text x="36" y="510" class="ct-group">the 52 mental factors · cetasika · චෛතසික — what colours a citta</text>
        <text x="36" y="530" class="ct-small">a citta never arises bare. these are what make one moment of consciousness differ from the next.</text>
        <rect x="36" y="540" width="1128" height="216" rx="10" class="ct-rect"/>
        ${CETASIKA.map(cetasikaRow).join("")}
        <text x="56" y="744" class="ct-small">7 + 6 + 14 + 25 = 52. and one citta at a time — never two at once, however it feels.</text>
      </svg>
    </div>
    <p class="board-hint">Wide board — drag it sideways to see the rest.</p>

    <div class="sim" data-decoder>
      <div class="sim__head">
        ${icon("khandha")}
        <span class="sim__title">Build a citta out of its fields</span>
        <span class="sim__sub">three switches, eight results</span>
      </div>

      <div class="sim__controls">
        <button class="dg-btn is-on" data-mode="lobha">greed-rooted · ලෝභමූලික</button>
        <button class="dg-btn" data-mode="mahakusala">wholesome · මහා කුසල</button>
      </div>

      <div class="decoder" data-fields></div>

      <div class="dg-readout" data-out></div>
    </div>

    <div class="machine__panel" data-panel>
      <div class="machine__phead">
        <span class="machine__picon" data-picon>${icon("khandha")}</span>
        <span class="machine__pname" data-pname>eighty-nine, or a hundred and twenty-one</span>
        <span class="machine__ppali" data-ppali>citta</span>
        <span class="machine__psi" data-psi>සිත</span>
        <span class="machine__psys" data-psys>the generated set</span>
      </div>
      <p class="machine__prole" data-prole>
        One citta arises at a time, does its work, and passes — and the next one
        is conditioned by it. Click any block above to open it. The two switchable
        sets below are worth the most attention: they show that the tradition was
        not cataloguing mind states one by one, it was specifying the fields that
        generate them.
      </p>
      <p class="machine__pnote" data-pnote>
        Source layer: the Abhidhammattha Saṅgaha, not the suttas — the same
        caveat the micro board carries.
      </p>
      <ul class="machine__pex" data-pex></ul>
      <a class="machine__plink" data-plink href="#/micro">See where these run &rarr;</a>
    </div>
  </div>`;
}

/* ---------- interactivity ---------- */

const DEFAULT_PANEL = {
  label: "eighty-nine, or a hundred and twenty-one",
  pali: "citta", si: "සිත", sys: "the generated set", ch: "micro",
  role:
    "One citta arises at a time, does its work, and passes — and the next one is conditioned by it. Click any block above to open it. The two switchable sets below are worth the most attention: they show that the tradition was not cataloguing mind states one by one, it was specifying the fields that generate them.",
  note:
    "Source layer: the Abhidhammattha Saṅgaha, not the suttas — the same caveat the micro board carries.",
  ex: [],
  link: "See where these run →",
};

export function wireCittas(el) {
  const mods = [...el.querySelectorAll(".ct-mod")];
  const fieldsEl = el.querySelector("[data-fields]");
  const out = el.querySelector("[data-out]");
  let mode = "lobha";
  const bits = { feeling: 0, view: 0, prompt: 0 };

  const p = {
    name: el.querySelector("[data-pname]"),
    pali: el.querySelector("[data-ppali]"),
    si: el.querySelector("[data-psi]"),
    sys: el.querySelector("[data-psys]"),
    role: el.querySelector("[data-prole]"),
    note: el.querySelector("[data-pnote]"),
    ex: el.querySelector("[data-pex]"),
    link: el.querySelector("[data-plink]"),
  };

  function paint(o) {
    p.name.textContent = o.label;
    p.pali.textContent = o.pali;
    p.si.textContent = o.si;
    p.sys.textContent = o.sys;
    p.role.textContent = o.role;
    p.note.textContent = o.note;
    p.ex.innerHTML = (o.ex || []).map((e) => `<li>${e}</li>`).join("");
    p.link.href = `#/${o.ch}`;
    p.link.textContent = o.link || "Read the chapter →";
  }

  mods.forEach((m) => {
    const act = () => {
      mods.forEach((n) => n.classList.toggle("is-sel", n === m));
      const s = SPHERES.find((x) => x.id === m.dataset.sphere);
      const k = KAMA.find((x) => x.id === m.dataset.kama);
      if (s) {
        paint({
          label: s.label, pali: s.pali, si: s.si, sys: `${s.n} types`,
          role: s.d, note: "One of the four spheres. Every citta belongs to exactly one.",
          ex: [], ch: "cittas", link: "Read the chapter →",
        });
      } else if (k) {
        paint({
          label: k.label, pali: k.pali, si: k.si, sys: `${k.n} of the 54`,
          role: k.d,
          note: `Breaks into ${k.parts.map(([pp, , n]) => `${n} ${pp}`).join(", ")}.`,
          ex: k.parts.map(([pp, si, n, d]) => `<b>${n} ${pp}</b> <i>${si}</i> — ${d}`),
          ch: "cittas", link: "Read the chapter →",
        });
      }
    };
    m.addEventListener("click", act);
    m.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") { e.preventDefault(); act(); }
    });
  });

  function renderFields() {
    const d = DECODERS[mode];
    fieldsEl.innerHTML = d.fields
      .map(
        (f) => `
        <div class="decoder__field">
          <span class="decoder__flabel">${f.label} <i>${f.si}</i></span>
          <div class="decoder__opts" role="group" aria-label="${f.label}">
            ${f.opts
              .map(
                (o, i) => `
              <button class="decoder__opt${bits[f.key] === i ? " is-on" : ""}"
                      data-field="${f.key}" data-val="${i}">
                <span class="decoder__optpali">${o[0]}</span>
                <span class="decoder__optsi">${o[1]}</span>
                <span class="decoder__optplain">${o[2]}</span>
              </button>`
              )
              .join("")}
          </div>
        </div>`
      )
      .join("");

    fieldsEl.querySelectorAll(".decoder__opt").forEach((b) => {
      b.addEventListener("click", () => {
        bits[b.dataset.field] = Number(b.dataset.val);
        renderFields();
        renderOut();
      });
    });
  }

  function renderOut() {
    const d = DECODERS[mode];
    const r = decode(mode, bits);
    out.innerHTML = `
      <div class="decoder__num">citta ${r.i + 1} <span>of 8 · ${d.pali}</span></div>
      <div class="decoder__name">${r.name}</div>
      <div class="decoder__si">${r.si}</div>
      <div class="decoder__plain">${r.plain}</div>
      <div class="decoder__ex">${r.ex}</div>
      <div class="decoder__note">${d.note}</div>`;
  }

  el.querySelectorAll("[data-mode]").forEach((b) => {
    b.addEventListener("click", () => {
      mode = b.dataset.mode;
      el.querySelectorAll("[data-mode]").forEach((x) =>
        x.classList.toggle("is-on", x === b)
      );
      renderFields();
      renderOut();
    });
  });

  renderFields();
  renderOut();
  paint(DEFAULT_PANEL);

  void MOTION;
  void iconAt;
}
